### ISSUE TITLE
yes

### ISSUE THREAD

**Issue by ThonkPT** [ytmcgamer/maven-offsets#1]
imma waste the rest of the day doing even do i dont need the offsets at all

**Comment by ThonkPT** [comment]
this is disappointing i thought it was 26 link vertises with adfly but its not this a lie reported to 911

**Comment by ThonkPT** [comment]
reopening in hopes u fix this

**Comment by ytmcgamer** [comment]
oh sorry i forgot my 784523 linkvertise links np thanks doing rn
